# Generated by Django 3.0.1 on 2020-06-27 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('color', models.CharField(max_length=7, verbose_name='Код цвета (например #FFFFFF)')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Основная цена')),
                ('price_discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена со скидкой')),
                ('img1', models.ImageField(null=True, upload_to='static/images/products/', verbose_name='Основное изображение')),
                ('img2', models.ImageField(null=True, upload_to='static/images/products/', verbose_name='Второе изображение')),
                ('img3', models.ImageField(null=True, upload_to='static/images/products/', verbose_name='Третье изображение')),
                ('img4', models.ImageField(null=True, upload_to='static/images/products/', verbose_name='Четвертое изображение')),
                ('img5', models.ImageField(null=True, upload_to='static/images/products/', verbose_name='Пятое изображение')),
                ('brand', models.CharField(max_length=200, verbose_name='Бернд')),
                ('availability', models.BooleanField(verbose_name='Наличие')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='mebel.Categories', verbose_name='Категория')),
                ('colors', models.ManyToManyField(related_name='colors', to='mebel.Colors', verbose_name='Цвета')),
                ('materials', models.ManyToManyField(related_name='materials', to='mebel.Materials', verbose_name='Материалы')),
                ('sizes', models.ManyToManyField(related_name='sizes', to='mebel.Sizes', verbose_name='Размеры')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
