# Generated by Django 3.0.1 on 2020-06-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0002_colors_materials_products_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
