# Generated by Django 3.0.1 on 2020-06-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0003_auto_20200628_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/products/', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/products/', verbose_name='Второе изображение'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/products/', verbose_name='Третье изображение'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/products/', verbose_name='Четвертое изображение'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/products/', verbose_name='Пятое изображение'),
        ),
    ]
