# Generated by Django 3.0.1 on 2020-06-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0004_auto_20200628_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
