# Generated by Django 3.0.1 on 2020-06-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0005_auto_20200629_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='new',
            field=models.BooleanField(default=True, verbose_name='Новинка'),
            preserve_default=False,
        ),
    ]
