# Generated by Django 3.0.1 on 2020-07-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0006_products_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='slug',
            new_name='slug_product',
        ),
        migrations.AddField(
            model_name='categories',
            name='slug_category',
            field=models.SlugField(default='123'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/products/', verbose_name='Основное изображение (640х480)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/products/', verbose_name='Второе изображение (640х480)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/products/', verbose_name='Третье изображение (640х480)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/products/', verbose_name='Четвертое изображение (640х480)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/products/', verbose_name='Пятое изображение (640х480)'),
        ),
    ]
