# Generated by Django 3.0.1 on 2020-07-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0007_auto_20200706_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug_category',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
    ]
