# Generated by Django 2.2.12 on 2020-07-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0008_auto_20200706_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.CharField(max_length=200, verbose_name='Ссылка')),
                ('img', models.ImageField(blank=True, null=True, upload_to='static/images/portfolio/', verbose_name='Изображение для портфолио')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
    ]
