# Generated by Django 2.2.12 on 2020-07-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0009_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=200, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Заявка на подписку',
                'verbose_name_plural': 'Заявки на подписку',
            },
        ),
    ]
