# Generated by Django 2.2.12 on 2020-07-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0010_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
    ]
