# Generated by Django 2.2.12 on 2020-07-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0011_subscribe_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('img', models.ImageField(null=True, upload_to='static/images/team/', verbose_name='Фото участника команды')),
                ('status', models.CharField(max_length=200, verbose_name='Статус')),
                ('phone', models.CharField(blank=True, max_length=200, verbose_name='Номер телефона')),
                ('instagram', models.CharField(blank=True, max_length=200, verbose_name='Ссылки на instagram')),
                ('mail', models.CharField(blank=True, max_length=200, verbose_name='Почта участника')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команда',
            },
        ),
    ]
