# Generated by Django 2.2.12 on 2020-07-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0012_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('img', models.ImageField(upload_to='static/images/team/', verbose_name='Фото человека с отзыва')),
                ('description', models.CharField(max_length=200, verbose_name='Отзыв')),
            ],
        ),
    ]
