# Generated by Django 2.2.12 on 2020-07-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0013_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Отзыв'),
        ),
    ]
