# Generated by Django 2.2.12 on 2020-07-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0014_auto_20200719_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='slug',
            new_name='url',
        ),
    ]
