# Generated by Django 3.1 on 2020-08-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0015_auto_20200720_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='popularity',
            field=models.BooleanField(default=False),
        ),
    ]
